modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="riskofinven"
version="${file.jarVersion}"
displayName="Risk of Inventory"
logoFile="riskofinven.png"
credits="Thanks to Risk of Rain, Sophisticated Backpacks, Simply Backpacks, and MinecraftByExample for making this mod possible."
authors="xMaximusKl"
description='''
An inventory mod to store Risk of Rain items and Totem of Undying
'''

[[dependencies.riskofinven]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.riskofinven]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.riskofinven]]
    modId="riskofrainmod"
    mandatory=false
    versionRange="[1.1.3,)"
    ordering="NONE"
    side="BOTH"